"""Generate the Vancouver-style reference list for the landing page.

Every report URL is read from `sources.py` -- the same registry the fetcher
uses -- so the reference list cannot drift away from what the code actually
downloaded. Retyping URLs by hand is exactly how a bibliography ends up citing
a document the pipeline never read.

Both networks are cited: the three ICMR-AMRSN editions and all eight NCDC
NARS-Net editions. The two are cited differently because the two publishers
print different things, which `ncdc_report_references` sets out.

Usage:
    python -m src.references            # print the rendered HTML
    python -m src.references --inject   # write it into index.html
"""

from __future__ import annotations

import argparse
import html
import sys

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

from .sources import NARSNET_SOURCES, REPO_ROOT, SOURCES

START = "<!-- REFERENCES:START (generated by src/references.py) -->"
END = "<!-- REFERENCES:END -->"

EDITION_ORDINAL = {2022: "6th", 2023: "7th", 2024: "8th"}

MONTHS = ("Jan", "Feb", "Mar", "Apr", "May", "Jun",
          "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")


class Reference:
    def __init__(self, text, url):
        self.text = text
        self.url = url


def icmr_report_references():
    """One entry per ICMR AMRSN edition actually ingested, oldest first."""
    refs = []
    for year in sorted(SOURCES):
        src = SOURCES[year]
        edition = EDITION_ORDINAL.get(year, src.edition)
        refs.append(
            Reference(
                "Indian Council of Medical Research. Annual report: "
                "Antimicrobial Resistance Research and Surveillance Network, "
                "January {y} to December {y}. {ed} ed. New Delhi: Indian "
                "Council of Medical Research; {y}.".format(y=year, ed=edition),
                src.url,
            )
        )
    return refs


NCDC_PUBLISHER = (
    "New Delhi: National Centre for Disease Control, Directorate General of "
    "Health Services, Ministry of Health and Family Welfare, Government of India"
)

# A printed publication date exists for two editions only, on the cover page:
# July 2022 for the 2021-data report and July 2023 for the 2022-data one. No
# other edition prints one anywhere in its front matter.
NCDC_PUBLICATION_YEAR = {2021: 2022, 2022: 2023}

# What every NARS-Net edition does NOT carry: no suggested-citation block, no
# ISBN, no DOI, no report number, no named authors or editors, and -- for six
# of the eight -- no publication date. Checked in the front matter of all
# eight. So `doi` and `isbn` stay unset, the author is corporate, and the six
# undated editions carry "[date unknown]" rather than a year inferred from the
# pattern the two dated ones set. The cover year is never used as a substitute:
# it is wrong for two editions in the series, the 2019-data report reading
# "AMR Annual report -2020" and the 2020-data one "Annual Report-2021".
NCDC_DATE_UNKNOWN = "[date unknown]"


def _cited(verified_on):
    """"2026-09-01" -> "2026 Sep 1", the Vancouver accessed-date form.

    NCDC URLs have already migrated twice and citations published in 2022-2024
    already point at dead links, so the access date is not decoration here --
    it is the only thing that dates the bytes these numbers were read from.
    """
    year, month, day = (int(part) for part in verified_on.split("-"))
    return "{} {} {}".format(year, MONTHS[month - 1], day)


def ncdc_report_references():
    """One entry per NCDC NARS-Net edition ingested, oldest first.

    Cited by REPORTING PERIOD, spelled out in the title, because the cover year
    is unreliable and because nothing else in these documents identifies an
    edition -- they carry no ordinal, so "8th ed." has no NARS-Net counterpart.
    """
    refs = []
    for year in sorted(NARSNET_SOURCES):
        src = NARSNET_SOURCES[year]
        published = NCDC_PUBLICATION_YEAR.get(year, NCDC_DATE_UNKNOWN)
        refs.append(
            Reference(
                "National Centre for Disease Control. National Antimicrobial "
                "Resistance Surveillance Network (NARS-Net) annual report: "
                "reporting period January-December {y} [Internet]. {pub}; "
                "{published} [cited {cited}].".format(
                    y=year,
                    pub=NCDC_PUBLISHER,
                    published=published,
                    cited=_cited(src.verified_on),
                ),
                src.url,
            )
        )
    return refs


def methodology_references():
    """Sources underpinning claims made in this repository's own prose.

    The i-AMRSS paper is what substantiates the note, repeated in the
    README and DATA_LICENSE.md, that isolate-level data is not yet publicly
    released. It says so in terms: "The data in the system are not yet publicly available.
    However, the reports generated from the data are annually updated on the
    ICMR's Antimicrobial Resistance website."
    """
    return [
        Reference(
            "Kaur J, Dhama AS, Buttolia H, Kaur J, Walia K, Ohri V, Kumar V, "
            "Lynn AM, Srivastava A, Singh H. ICMR's Antimicrobial Resistance "
            "Surveillance system (i-AMRSS): a promising tool for global "
            "antimicrobial resistance surveillance. JAC Antimicrob Resist. "
            "2021;3(1):dlab023. doi:10.1093/jacamr/dlab023.",
            "https://doi.org/10.1093/jacamr/dlab023",
        ),
    ]


def all_references():
    return (
        icmr_report_references()
        + ncdc_report_references()
        + methodology_references()
    )


def render_html(refs=None) -> str:
    refs = refs if refs is not None else all_references()
    items = []
    for ref in refs:
        url = html.escape(ref.url, quote=True)
        items.append(
            '        <li class="ref">{text} Available from: '
            '<a href="{url}">{shown}</a></li>'.format(
                text=html.escape(ref.text, quote=False), url=url, shown=url
            )
        )
    return (
        "      <ol class=\"reflist\">\n" + "\n".join(items) + "\n      </ol>"
    )


def inject(path=None) -> bool:
    path = path or (REPO_ROOT / "index.html")
    page = path.read_text(encoding="utf-8")
    if START not in page or END not in page:
        raise SystemExit(
            "{} has no {} / {} markers to write between.".format(path, START, END)
        )
    head, rest = page.split(START, 1)
    _old, tail = rest.split(END, 1)
    updated = head + START + "\n" + render_html() + "\n      " + END + tail
    if updated == page:
        print("references already up to date")
        return False
    path.write_text(updated, encoding="utf-8")
    print("updated {} with {} references".format(path, len(all_references())))
    return True


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--inject", action="store_true", help="write into index.html")
    args = ap.parse_args(argv)
    if args.inject:
        inject()
    else:
        print(render_html())
    return 0


if __name__ == "__main__":
    sys.exit(main())
