"""Generate the Vancouver-style reference list for the landing page.

Every ICMR report URL is read from `sources.py` -- the same registry the
fetcher uses -- so the reference list cannot drift away from what the code
actually downloaded. Retyping URLs by hand is exactly how a bibliography ends
up citing a document the pipeline never read.

Usage:
    python -m src.references            # print the rendered HTML
    python -m src.references --inject   # write it into index.html
"""

from __future__ import annotations

import argparse
import html
import sys

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

from .sources import REPO_ROOT, SOURCES

START = "<!-- REFERENCES:START (generated by src/references.py) -->"
END = "<!-- REFERENCES:END -->"

EDITION_ORDINAL = {2022: "6th", 2023: "7th", 2024: "8th"}


class Reference:
    def __init__(self, text, url):
        self.text = text
        self.url = url


def icmr_report_references():
    """One entry per ICMR AMRSN edition actually ingested, oldest first."""
    refs = []
    for year in sorted(SOURCES):
        src = SOURCES[year]
        edition = EDITION_ORDINAL.get(year, src.edition)
        refs.append(
            Reference(
                "Indian Council of Medical Research. Annual report: "
                "Antimicrobial Resistance Research and Surveillance Network, "
                "January {y} to December {y}. {ed} ed. New Delhi: Indian "
                "Council of Medical Research; {y}.".format(y=year, ed=edition),
                src.url,
            )
        )
    return refs


def methodology_references():
    """Sources underpinning claims made in this repository's own prose.

    The i-AMRSS paper is what substantiates the note, repeated in the
    README and DATA_LICENSE.md, that isolate-level data is not yet publicly
    released. It says so in terms: "The data in the system are not yet publicly available.
    However, the reports generated from the data are annually updated on the
    ICMR's Antimicrobial Resistance website."
    """
    return [
        Reference(
            "Kaur J, Dhama AS, Buttolia H, Kaur J, Walia K, Ohri V, Kumar V, "
            "Lynn AM, Srivastava A, Singh H. ICMR's Antimicrobial Resistance "
            "Surveillance system (i-AMRSS): a promising tool for global "
            "antimicrobial resistance surveillance. JAC Antimicrob Resist. "
            "2021;3(1):dlab023. doi:10.1093/jacamr/dlab023.",
            "https://doi.org/10.1093/jacamr/dlab023",
        ),
    ]


def all_references():
    return icmr_report_references() + methodology_references()


def render_html(refs=None) -> str:
    refs = refs if refs is not None else all_references()
    items = []
    for ref in refs:
        url = html.escape(ref.url, quote=True)
        items.append(
            '        <li class="ref">{text} Available from: '
            '<a href="{url}">{shown}</a></li>'.format(
                text=html.escape(ref.text, quote=False), url=url, shown=url
            )
        )
    return (
        "      <ol class=\"reflist\">\n" + "\n".join(items) + "\n      </ol>"
    )


def inject(path=None) -> bool:
    path = path or (REPO_ROOT / "index.html")
    page = path.read_text(encoding="utf-8")
    if START not in page or END not in page:
        raise SystemExit(
            "{} has no {} / {} markers to write between.".format(path, START, END)
        )
    head, rest = page.split(START, 1)
    _old, tail = rest.split(END, 1)
    updated = head + START + "\n" + render_html() + "\n      " + END + tail
    if updated == page:
        print("references already up to date")
        return False
    path.write_text(updated, encoding="utf-8")
    print("updated {} with {} references".format(path, len(all_references())))
    return True


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--inject", action="store_true", help="write into index.html")
    args = ap.parse_args(argv)
    if args.inject:
        inject()
    else:
        print(render_html())
    return 0


if __name__ == "__main__":
    sys.exit(main())
